pipeline {
    agent any
    tools {
        maven 'maven_3.6.3' 
    }
    stages 
    {
        stage('build') {
            
            	steps{
            			bat 'mvn clean package'
            		}
            }
            
         stage('deploy')
         {
         		steps{
         				withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: 'PCF_LOGIN',
						usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) 
						{

							sh 'cf login -a http://api.run.pivotal.io -u $USERNAME -p $PASSSWORD'
							sh 'cf push'
 						}
         
         			}
         	
         }
     }
}